build/pupmod-pam.spec, templates/etc/pam.d/auth.erb
This update moves pam_mkhomedir to higher in the stack than pam_systemd.
Systemd errors were occuring during login due to a lack of a home
directory for the user.
SIMP-393 #close
=> (SIMP-393) Fixed order of pam_mkhomedir

build/pupmod-pam.spec, manifests/init.pp, spec/classes/access_spec.rb, spec/classes/auth_spec.rb, spec/classes/init_spec.rb, spec/classes/limits_conf.rb, spec/classes/wheel_spec.rb, spec/defines/access/manage_spec.rb, spec/defines/limits/add_spec.rb, spec/spec_helper.rb, templates/etc/pam.d/auth.erb
This replaces the lsb* facts with operatingsystem* ones so that the
module can work in non-LSB compliant environments.
SIMP-556 #comment Update to use non-LSB compliant facts.
=> (SIMP-556) Replace lsb* facts

.fixtures.yml, .fixtures.yml.local, build/pupmod-pam.spec
Before this commit, common SIMP-related custom functions were been kept
in either `simp-common` or `simp-functions`, and the `concat` function
was provided by the `simp-concat` module.  These functions are now
provides by the `simp-simplib` and `simp-simpcat` modules, respectively.
This update replaces all requirements in the RPM spec file,
metadata.json, or .fixtures.yml to reflect the migration to the new
modules.
SIMP-601 #comment Migrated `pupmod-simp-pam`.
SIMP-604 #comment Updated `pupmod-simp-pam`.
=> (SIMP-604) Migrate to simplib and simpcat

manifests/init.pp
SIMP-652 #close #comment `$sssd::params` ref changed to `$pam::params`
=> (SIMP-652) Fix SSSD logic

build/pupmod-pam.spec, metadata.json, templates/etc/pam.d/auth.erb
pam_oddjob_mkhomedir was causing an ANOM_ABEND error which prevented
users from logging in over SSH.
When moved below the pam_ssh line, the logins were successful.
Disabling SELinux also allowed the user to login but this was not an
acceptable resolution.
SIMP-970 #close
=> (SIMP-970) Fix issue with pam_oddjob_mkhomedir

.puppet-lint.rc, CHANGELOG, manifests/auth.pp, manifests/init.pp, manifests/wheel.pp, metadata.json, spec/classes/init_spec.rb, spec/classes/wheel_spec.rb, spec/defines/auth_spec.rb, spec/expected/auth_spec/fingerprint-auth_custom_content, spec/expected/auth_spec/password-auth_custom_content, spec/expected/auth_spec/smartcard-auth_custom_content, spec/expected/auth_spec/system-auth_custom_content
- Added a generic content option to replace all templated PAM
configurations
- Setting use_templates to false will enable them
SIMP-768 #close
=> (SIMP-768) Add methods for adding content to PAM

manifests/init.pp, metadata.json
authconfig locations seem to be incorrect. if the intent is to remove the tools, they're located in /usr/sbin (as links to the python scripts in /usr/share) and not /etc/pam.d
=> (SIMP-2832) pam authconfig removal

CHANGELOG, build/rpm_metadata/requires, metadata.json
- Update concat version. concat 3.0.0 is fully backward compatible with 2.x.
- Add concat dependency to metadata.json
=> (SIMP-3613) pam: Update to concat 3.0.0

.fixtures.yml
Pin concat to 3.0.0 in .fixtures.yml, as metadata.json bounds
concat to < 4.0.0.
=> (SIMP-3613) pam: Pin concat to 3.0.0 in .fixtures.yml

CHANGELOG, manifests/init.pp, metadata.json, spec/classes/init_spec.rb, templates/etc/pam.d/sudo.epp
This commit manages the files `/etc/pam.d/sudo` and `/etc/pam.d/sudo-i`
and (when pam_tty_audit contains users) ensures that it contains the
following line:
```
session required pam_tty_audit.so disable=* enable=root open_only
```
SIMP-1246 #close
=> (SIMP-1246) Enable pam_tty_audit for sudo

.gitlab-ci.yml, .puppet-lint.rc, .travis.yml, CHANGELOG, manifests/init.pp, metadata.json, spec/expected/auth_spec/cracklib-fingerprint-auth_default_params, spec/expected/auth_spec/cracklib-fingerprint-auth_sssd_openshift_multi_tty_audit, spec/expected/auth_spec/cracklib-password-auth_default_params, spec/expected/auth_spec/cracklib-password-auth_sssd_openshift_multi_tty_audit, spec/expected/auth_spec/cracklib-password-separator-0, spec/expected/auth_spec/cracklib-password-separator-1, spec/expected/auth_spec/cracklib-password-separator-2, spec/expected/auth_spec/cracklib-password-separator-false, spec/expected/auth_spec/cracklib-smartcard-auth_default_params, spec/expected/auth_spec/cracklib-smartcard-auth_sssd_openshift_multi_tty_audit, spec/expected/auth_spec/cracklib-system-auth_default_params, spec/expected/auth_spec/cracklib-system-auth_sssd_openshift_multi_tty_audit, spec/expected/auth_spec/pwquality-fingerprint-auth_default_params, spec/expected/auth_spec/pwquality-fingerprint-auth_sssd_openshift_multi_tty_audit, spec/expected/auth_spec/pwquality-password-auth_default_params, spec/expected/auth_spec/pwquality-password-auth_sssd_openshift_multi_tty_audit, spec/expected/auth_spec/pwquality-password-separator-0, spec/expected/auth_spec/pwquality-password-separator-1, spec/expected/auth_spec/pwquality-password-separator-2, spec/expected/auth_spec/pwquality-password-separator-false, spec/expected/auth_spec/pwquality-smartcard-auth_default_params, spec/expected/auth_spec/pwquality-smartcard-auth_sssd_openshift_multi_tty_audit, spec/expected/auth_spec/pwquality-system-auth_default_params, spec/expected/auth_spec/pwquality-system-auth_sssd_openshift_multi_tty_audit
Change the minimum allowed UID to that defined in /etc/login.defs by
default or 1000 if nothing else is defined.
SIMP-4192 #comment Add consistency for the global min_uid settings
=> (SIMP-3892) Use login_defs.uid_min by default

spec/acceptance/suites/compliance/00_default_spec.rb
Discovered that Puppet 4.10.4+ breaks the compliance engine Hiera 3
backend.
=> (SIMP-4679) Convert to Hiera 5 for compliance test

Gemfile, manifests/limits.pp, spec/acceptance/suites/compliance/00_default_spec.rb, spec/acceptance/suites/default/20_check_limits_order_spec.rb, spec/expected/limits_acceptance/limits_conf_numeric
This updates the order value for the concat resource of /etc/security/limits.conf
to 'numeric' to ensure proper ordering of rule fragments.
Also updates simp-rspec-facts to version that includes OEL facts.
#Fixes SIMP-5478
=> (SIMP-5478) limits.conf ordering

CHANGELOG, manifests/access.pp, metadata.json
- Added pam::access::access_file_mode parameter to allow users to manage
access.conf file permissions
SIMP-6108 #close
=> (SIMP-6108) Allow users to manage access.conf permissions

CHANGELOG, manifests/config.pp, spec/acceptance/suites/default/00_default_spec.rb, spec/classes/config_spec.rb, spec/spec_helper.rb
- authselect is used in place of authconfig on EL8.  This
fix disables authselect if the disable_authconfig boolean
is set on EL8
- Update spec_helpers to run on FIPS
SIMP-7528 #close
SIMP-7580 #close
SIMP-7581 #close
SIMP-7377 #close
=> (SIMP-7528) Disable authselect

CHANGELOG, metadata.json, spec/expected/auth_spec/cracklib-password-auth_sssd_no_tty_audit, spec/expected/auth_spec/cracklib-password-auth_sssd_openshift_multi_tty_audit, spec/expected/auth_spec/cracklib-system-auth_sssd_no_tty_audit, spec/expected/auth_spec/cracklib-system-auth_sssd_openshift_multi_tty_audit, spec/expected/auth_spec/pwquality-password-auth_sssd_no_tty_audit, spec/expected/auth_spec/pwquality-password-auth_sssd_openshift_multi_tty_audit, spec/expected/auth_spec/pwquality-system-auth_sssd_no_tty_audit, spec/expected/auth_spec/pwquality-system-auth_sssd_openshift_multi_tty_audit, templates/etc/pam.d/auth.epp
- moved pam_unix.so check before pam_sss.so check in the
password section of the auth files.  It returns an
"authentication token manipulation" error  on el8
if pam_sss.so is checked before pam_unix.
SIMP-7605 #close
=> (SIMP-7605) EL8 bug: can't set local user password

.gitlab-ci.yml, .travis.yml, Gemfile
This patch updates the puppet and ruby versions in the Gitlab CI
pipeline to reflect the latest PE LTS releases.  Most notably, it adds
specific tests for PE2019.8 LTS.
SIMP-7897 #close
[SIMP-7848] #comment Add PE2019.8 to GL CI in pupmod-simp-pam
[SIMP-7855] #comment Update GL CI to PE2018.1.15 in pupmod-simp-pam
[SIMP-7848]: https://simp-project.atlassian.net/browse/SIMP-7848
[SIMP-7855]: https://simp-project.atlassian.net/browse/SIMP-7855
=> (SIMP-7848) Add PE2019.8 to pupmod-simp-pam GL pipeline

spec/acceptance/suites/default/20_check_limits_order_spec.rb
Fix a fix I made to the previous commit. Existing check for
limits.conf was running on only one host.
=> (SIMP-MAINT) Check limits.conf on all hosts

.github/workflows/pr_glci.yml, .github/workflows/pr_glci_manual.yml, .github/workflows/pr_tests.yml, .gitlab-ci.yml
This patch updates the standardized GitHub Actions that trigger GLCI
pipelines:
- Still preemptively cancels existing GLCI pipelines for the same
branch, EXCEPT when a pipeline is for the same commit hashref.
- Refactored common GLCI logic into new composite run steps actions:
- [github-action-gitlab-ci-pipeline-trigger@v1][0]
- [github-action-gitlab-ci-syntax-check@v1][1]
This patch also enforces the standardized asset baseline using
simp/puppetsync, and may apply other updates to ensure conformity.
CI: SKIP MATRIX
[SIMP-9321] #close
[SIMP-9266] #comment Standardized GHA + assets in pupmod-simp-pam
[SIMP-9279] #comment `.fixtures.yml` triggers GLCI acc for pupmod-simp-pam
[0]: https://github.com/simp/github-action-gitlab-ci-pipeline-trigger
[1]: …
=> (SIMP-9266) Improve GHA GCLI trigger in pupmod-simp-pam

CHANGELOG, spec/expected/auth_spec/cracklib-system-auth_oath_enabled, spec/expected/auth_spec/pwquality-system-auth_oath_enabled, templates/etc/pam.d/auth.epp
-  This adds the quiet parameter to pam_listfile entries in auth.pp so
service refusals are not logged as errors.
SIMP-9627 #close
=> (SIMP-9627) Add quiet to pam_listfile

spec/acceptance/nodesets/default.yml, spec/acceptance/nodesets/oel.yml, spec/acceptance/suites/security_modules/nodesets/default.yml, spec/acceptance/suites/security_modules/nodesets/oel.yml
- update the EL8 nodes in the acceptance tests
to run with generic/centos8 to make sure they using
CentOS 8.4
- update oel7 node to generic box from onyxpoint
SIMP-10204 #comment update pam
SIMP-10236
=> (SIMP-10204) Ensure testing with CentOS 8.4

.github/workflows/pr_glci.yml, .github/workflows/pr_glci_cleanup.yml, .github/workflows/pr_glci_manual.yml, .github/workflows/pr_tests.yml, .github/workflows/release_rpms.yml, .github/workflows/tag_deploy.yml, .gitlab-ci.yml, Gemfile
This patch updates GHA workflows to:
* remove the deprecated `ubuntu-18.02` machine
* update actions that support nodejs 16 instead of 12
- `actions/checkout@v3`
- `actions/github-script@v6`
- this includes necessary fixes to breaking changes in github-script
code ([0])
* migrate from `::set-output` to the new `$GITHUB_OUT` variable ([1])
It updates the features of the `release_rpms` workflow to:
* add a new `rebuild_number` parameter to enable building RPMs with
arbitrary release numbers (example: `-2`)
* temporarily remove the `verbose` parameter (max parameters = 12)
The patch enforces a standardized asset baseline using simp/puppetsync,
and may also apply other updates to ensure conformity.
[0]: https://github.com/actions/github-script#breaking-changes-in-v5
[1]: …
=> Update GHA workflows to supported practices

.gitlab-ci.yml, Gemfile
This patch updates GHA workflows to use GCP as a hypervisor when
BEAKER_HYPERVISOR is `google`
The patch enforces a standardized asset baseline using simp/puppetsync,
and may also apply other updates to ensure conformity.
=> Add GCP support to GLCI

CHANGELOG, manifests/auth.pp, manifests/config.pp, manifests/init.pp, metadata.json
When using the pam module while authselect is enabled files will be created in a location that will be included by authselect rather than being overwritten.
=> (#132) Added support for authselect

.github/workflows/pr_tests.yml, .gitignore, .gitlab-ci.yml, .puppet-lint.rc, Gemfile, REFERENCE.md
This patch adds support for RockyLinux 8
The patch enforces a standardized asset baseline using simp/puppetsync,
and may also apply other updates to ensure conformity.
=> Finalize RockyLinux 8 support
